import Link from "next/link";
import type { ReactNode } from "react";

export function Header() {
  return <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="flex items-center gap-3 font-bold text-slate-950"><span className="grid size-10 place-items-center rounded-2xl bg-blue-700 text-white">SE</span><span>School Events</span></Link><nav className="hidden items-center gap-6 text-sm font-medium text-slate-600 md:flex"><Link href="/events">Sự kiện</Link><Link href="/calendar">Lịch</Link><Link href="/student">Sinh viên</Link><Link href="/admin">Quản trị</Link></nav><Link href="/login" className="rounded-full bg-slate-950 px-5 py-2 text-sm font-semibold text-white">Đăng nhập</Link></div></header>;
}
export function Footer() { return <footer className="border-t border-slate-200 bg-white px-6 py-10 text-sm text-slate-500"><div className="mx-auto flex max-w-7xl flex-col gap-2 md:flex-row md:items-center md:justify-between"><p>© 2026 School Events — Hệ thống quản lý sự kiện đại học.</p><p>Quản lý đăng ký, điểm danh QR, phân công và báo cáo.</p></div></footer>; }
export function PageShell({ children }: { children: ReactNode }) { return <main className="mx-auto w-full max-w-7xl flex-1 px-6 py-10">{children}</main>; }
export function SectionTitle({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) { return <div className="mb-8 max-w-3xl">{eyebrow ? <p className="mb-2 text-sm font-bold uppercase tracking-[0.2em] text-blue-700">{eyebrow}</p> : null}<h1 className="text-3xl font-bold tracking-tight text-slate-950 md:text-5xl">{title}</h1>{description ? <p className="mt-4 text-lg leading-8 text-slate-600">{description}</p> : null}</div>; }
export function StatCard({ label, value, hint }: { label: string; value: string | number; hint?: string }) { return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold text-slate-950">{value}</p>{hint ? <p className="mt-2 text-sm text-slate-500">{hint}</p> : null}</div>; }
export function Badge({ children, tone = "blue" }: { children: ReactNode; tone?: "blue" | "green" | "amber" | "slate" | "red" }) { const colors = { blue: "bg-blue-50 text-blue-700 ring-blue-200", green: "bg-emerald-50 text-emerald-700 ring-emerald-200", amber: "bg-amber-50 text-amber-700 ring-amber-200", slate: "bg-slate-100 text-slate-700 ring-slate-200", red: "bg-rose-50 text-rose-700 ring-rose-200" }; return <span className={"inline-flex rounded-full px-3 py-1 text-xs font-bold ring-1 " + colors[tone]}>{children}</span>; }
export function Field({ label, placeholder, type = "text", name, required = false, defaultValue }: { label: string; placeholder?: string; type?: string; name?: string; required?: boolean; defaultValue?: string }) { return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<input name={name} required={required} type={type} placeholder={placeholder} defaultValue={defaultValue} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></label>; }
export function SelectField({ label, options, name, defaultValue }: { label: string; options: string[]; name?: string; defaultValue?: string }) { return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}<select name={name} defaultValue={defaultValue} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
export function TextareaField({ label, placeholder, name, required = false, defaultValue }: { label: string; placeholder?: string; name?: string; required?: boolean; defaultValue?: string }) { return <label className="grid gap-2 text-sm font-semibold text-slate-700 md:col-span-2">{label}<textarea name={name} required={required} rows={5} placeholder={placeholder} defaultValue={defaultValue} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></label>; }
export function DataTable({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) { return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><table className="w-full border-collapse text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{headers.map((header) => <th key={header} className="px-5 py-4 font-bold">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => <tr key={index} className="text-slate-700">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-5 py-4">{cell}</td>)}</tr>)}</tbody></table></div>; }
